### ISSUE TITLE
Enable Linux VM via Horizon VMware

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#10]
Remove desktop in Windows VMs (via Horizon VMware) is a lot better than in Linux VMs (via thinlink). We would like to try pilot Linux VM on Horizon VM interface. 

A workaround is to use Horizon VMware client to connect to Windows VM, open Putty, and ssh to linux VMs. I guess it's also possible to ssh to p33-submit. 
If you know a better ssh client for Windows than Putty let's ask TSD to install it.
If you want to use WinSCP let's ask them to enable it - it's already available for p697.

**Comment by tobias-kaufmann** [comment]
Just to add: We've had quite a bit of trouble with thinlink VMs, e.g.
1. being kicked out and not able to log back on. Sometimes we can then still log into it through putty and terminate our session but it does not work all the time. 
2. Keyboard issues
3. Slow machine
Moving to Horizon might solve some of these things.

**Comment by ofrei** [comment]
Discussed at today's TSD meeting. Linux VMs on Horizon VM Ware are in beta-testing, and may enter production later this year - but there is some uncertainty.

**Comment by ofrei** [comment]
``p33-rhel-01-pool`` machine (Linux on VMWare) is available for pilot testing. Please report here if you face any issues.
![image](https://user-images.githubusercontent.com/13171449/96965487-8af47700-150c-11eb-8b6e-94e201c3819a.png)

**Comment by ofrei** [comment]
- I've only had the norwegian keyboard layout on p33-rhel7-01-pool, and couldn't find how to switch to english.
- I have a 4K screen, and couldn't find how to set the "scale" on the remote desktop to enlarge fonts, icons, etc

**Comment by Sandeek** [comment]
There is an issue logging in to the Linux VMs with an error reporting all available desktop sources to access the VMs are busy.
![image](https://user-images.githubusercontent.com/71389186/96994172-9b1c4e80-152c-11eb-9852-97da261b4d7d.png)

**Comment by fuyu00** [comment]
I get the same issue.
![image](https://user-images.githubusercontent.com/45471612/96999075-e63a5f80-1534-11eb-9750-bfc5487148cb.png)

**Comment by ofrei** [comment]
@Sandeek Now we have two Linux VMs on Horizon VMWare, RHEL7 and RHEL8.  Are they working well?

**Comment by pierreberthet** [comment]
I still can not sign in, last week until Wednesday perhaps I was able to,
now I can not anymore, to my active session on rhel8. My login details
seem to not be recognised anymore.
Logging on rhel7 just fails while "loading Desktop" in VMWare, telling me
it is too busy.

**Comment by fuyu00** [comment]
Managed to sign in - 
issues: 
- the login screen seems to default to a Norwegian keyboard layout, that might explain the issue with credentials no longer being recognised?
- For some reason neither RStudio nor VSCode are available on either rhel 7 or 8 through VMWare Horizon

**Comment by ofrei** [comment]
This is an old thread, most recent ticket for this is https://github.com/norment/tsd_issues/issues/67
