### ISSUE TITLE
Approve OTP token on mobile phone without typing

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#13]
I have to type OTP token quite frequently, particularly when using tsd-s3cmd.
It would be nice to be able to approve OTP without typing anything, e.g. by clicking on some push notification on a mobile phone - similar to BankID på mobil. I've seen this on other clusters e.g. via  an app by https://duo.com/

**Comment by ThomasDoug** [comment]
Issue for 12.02 meet @ USIT
