### ISSUE TITLE
Cluster software is not available on login node

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#17]
In p33 we have a custom solution where /cluster is mounted on the login node. However, this is not the default setting - all other projects need to use "ssh pNN-submit" to get access to the cluster. This also means that we can't use "module load" on the login node, which is limiting.

**Comment by tobias-kaufmann** [comment]
Not sure I understand @ofrei: in RHEL7 thinlink it is no problem to load modules.

**Comment by ofrei** [comment]
@tobias-kaufmann this is not an issue for p33, because for that specific project TSD have implemented a custom solution: we do see the ``/cluster`` on login nodes, and can submit colossus jobs from the login node. Therefore p33-submit became kind of redundant. Currently this is different on other projects, including p697, p830 and p970. The question is whether we should ask to implement p33 solution also for other projects, or just wait until #8 is resolved (and that might take care of everything else).

Info from Haneef:
> Back in April 2019, when Colossus was upgraded, we decided to
> standardize a dedicated submit-host in each project using Colossus.
> The benefits among others are to not saturate resources on login hosts
> (p697-tl01-l), and it is easier to reboot(p697-submit), when
> necessary, as by doing this, it does not affect all the users in p697.
> There was also an issue with RHEL6 vs RHEL7. But then again, there are
> always exceptions, and p33 was one of those exceptions.

**Comment by ofrei** [comment]
Closing this ticket because "Cluster software is not available on login node" is by design (except for RHEL7 thinlink vm, specific to p33).
