### ISSUE TITLE
Dedicated cores

### ISSUE THREAD

**Issue by tobias-kaufmann** [norment/tsd_issues#18]
It might help to split the NORMENT dedicated cores into two queues, one for testing out scripts and one for processing data. We rarely need all cores for testing scripts, but we'd also like to keep some cores dedicated to testing so that a test script will start immediately without queue.

**Comment by danielroelfs** [comment]
Seconded!

**Comment by ofrei** [comment]
Discussed at today's TSD meeting. They encourage us to create a ticker for that. Other TSD projects are interested too. But it may take some time to implement (it's not straighforward due to the way dedicated queues are implemented - but there is a clear need for this scenario).

**Comment by ofrei** [comment]
Tracked by [rt.uio.no #3764495] Automatisk svar (AutoReply): Dev queue for project-owned reservations (p33 project)

**Comment by ofrei** [comment]
This should be now implemented. Reply from TSD support ticket:

```
... created a reservation "norment_dev" now.  You can see it in the output of qsumm.

The new reservation is used the same way that the norment reservation is used:

   sbatch -A p33_norment_dev ...

and similarly for p697.  Note that the old way of using the reservation (-A p33 --reservation=norment_dev) does not work.  It will be removed for all reservations shortly.
```

**Comment by ofrei** [comment]
Solved.
