### ISSUE TITLE
p33 cluster is at its capacity

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#2]
As of today we even exceed our capacity (no idea how that's possible...)
![image](https://user-images.githubusercontent.com/13171449/74053368-f4167780-49db-11ea-95a1-77346cfc836e.png)

**Comment by tobias-kaufmann** [comment]
We have cleared some space now, but new data is available for processing, so we will be out of space again rapidly.

**Comment by ofrei** [comment]
Discussed at today's meeting with TSD. Unfortunately it will not be possible to get more storage on ``/cluster`` until new HPC storage is in production (i.e. #8). But for now we could try to do a cleanup. We can also  ask for more space on ``/durable`` - that should be possible.

**Comment by ofrei** [comment]
As a temporary solution, TSD increased our quota on /durable.  To do so they removed legacy /export and /import folders. 
We should get more space on /cluster once TSD finalize their new HPC system.

**Comment by ofrei** [comment]
This is resolved in August'20, we got 600 TB.
