### ISSUE TITLE
TSD users not affiliated with UiO can't run MATLAB within TSD

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#20]
This is a very hard hard issue to solve. Maybe we can try OCTAVE?

**Comment by ofrei** [comment]
Another option might be to compile MATLAB code into binary.
https://se.mathworks.com/products/compiler.html

**Comment by Sandeek** [comment]
Hi Alex, recently one more user had this issue. If the user account is not affiliated to UiO, then TSD suggests that the user bring his own matlab license. Is it a fair enough solution?

**Comment by ofrei** [comment]
I don't have experience with "Bring your own license" feature that TSD could offer for non-UiO matlab users. It sounds reasonable - but of course depends on whether the user has MATLAB license. 
Could you double-check which MATLAB software the user would like to run? If it is a specific software one option is to do as suggested here https://github.com/comorment/gwas/issues/10

**Comment by ofrei** [comment]
Can we ask TSD to provide more documentation on "bring your own license"?
