### ISSUE TITLE
Lack of information about queueing system

### ISSUE THREAD

**Issue by denvdm** [norment/tsd_issues#21]
Very few, if any, of us fully understands the inner workings of the queueing system, there should be clearer guidelines, e.g. about how to optimize job specifications and what may slow down the system. 
As example, I think we´ve all had this frustrating experience where we submit jobs and they just stand hours in queue, with nothing happening. Checking qsumm sometimes then shows p33 running (yes, status running) e.g. 800 jobs, while none are listed by squeue. Is this a bug? Is there something wrong with our job specifications? Unclear.

**Comment by ofrei** [comment]
Yeah, true. To me SLURM scheduling policy is quite cryptic - not just TSD but also Abel / SAGA. I've read through https://slurm.schedmd.com/priority_multifactor.html , but it kind of useless without having access to the exact ``slurm.conf`` file.

**Comment by ofrei** [comment]
It's possible to run ``sshare -a -l`` on tsd to get some more info:
![image](https://user-images.githubusercontent.com/13171449/74388652-34bb2a00-4dfc-11ea-98a9-f74a62cb0f07.png)
But these numbers are not clear to me.

**Comment by ofrei** [comment]
I think it's fair to close this: queue system is documented here: https://www.uio.no/english/services/it/research/sensitive-data/use-tsd/hpc/queue-system.html , and we have further notes here: http://norment.awiki.org/dokuwiki/tsd_hpc_sessions . If there are more specific questions please re-open.
