### ISSUE TITLE
Mail list for internal TSD announcements

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#27]
Do we have the list?
The announcements could be something like "p697-submit machine is going to be rebooted in 30 minutes. Please save your work or let us know ASAP if the reboot needs to be postponed."

**Comment by ofrei** [comment]
We have ``tsd-p33@medisin.uio.no``, should we also use it for p697 and the other projects?  Or  rename it to ``tsd-norment@medisin.uio.no``? I think it's best with one mail list (not per project)...

**Comment by ThomasDoug** [comment]
Agree, let's keep it like it is for now. Most issues will remain relevant only for p33

**Comment by ofrei** [comment]
Solved, we agreed to use tsd-p33 for all TSD-related announcements for all our projects (p697, etc)
