### ISSUE TITLE
file directory write permissions

### ISSUE THREAD

**Issue by scimerc** [norment/tsd_issues#28]
users are currently permitted to write in the `/tsd/p33/data/durable` and `/cluster/projects/p33` areas because we can only set permissions below such levels. the idea is to assign ownership of these areas to `p33-serviceuser` and write-lock them to prevent the proliferation of forgotten and undeletable garbage in the common area.

**Comment by ofrei** [comment]
This had been discussed with TSD several times but they couldn't implement .
