### ISSUE TITLE
RStudio freeze

### ISSUE THREAD

**Issue by tirilgurholt** [norment/tsd_issues#30]
RStudio will occasionally freeze with a gray screen, and it is difficult to kill the process (top -> kill pid) or via GUI (quit session, CTRL+Q).  

This hang is from yesterday (see screenshot), and I have tried various stuff to kill this RStudio process. It is possible to start new RStudio sessions, but not possible to close the old one...  

![Skjermbilde 2020-02-18 kl  14 08 24](https://user-images.githubusercontent.com/12950028/74739200-a2ca7b80-5258-11ea-8a03-216968b5c8cf.png)

**Comment by ofrei** [comment]
Please reopen if this is still an issue.
