### ISSUE TITLE
Try REDcap

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#37]
It would be great to evaluate existing software solutions like REDcap ( https://www.project-redcap.org/ ) as a long-term alternative to NoDa.

**Comment by ofrei** [comment]
We got license for REDcap,  things move forward.
 Can we use something like this https://github.com/si-medbif/redcap-docker-compose - either Docker or Singularity image to deploy REDcap wtihin TSD?

**Comment by Sandeek** [comment]
The project would be tracked on https://github.com/norment/redcap
