### ISSUE TITLE
FSL pipeline doesn't run on TSD

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#4]
I don't know details but it seem to be a big issue..

**Comment by tobias-kaufmann** [comment]
_Description_: FSL pipeline for analyzing fMRI data from raw data to fully processed networks used to run on the old system but fails on colossus 3.  We are seeing errors in the beginning of the pipeline (feat) but it will likely be more errors later on in the pipeline. 
_Priority level_: Getting FSL to run is quite central for several ongoing projects in the imaging group and as soon as the software is working again, we will feed thousands of images through the pipeline.
_Status_: TSD support is already working on a solution!

**Comment by tobias-kaufmann** [comment]
Update: FSL 6.0.3 has now been deployed by TSD support and can be loaded using 
source /cluster/software/fsl/6.0.3/setup.source
A first test of feat succeeded. We will now test the rest of the FSL pipeline.

**Comment by ofrei** [comment]
@tobias-kaufmann was this resolved?

**Comment by tobias-kaufmann** [comment]
Not yet. FSL Feat runs smoothly I think but some libraries are missing for FSL Fix/Aroma.

**Comment by ofrei** [comment]
As we discussed today this is fixed by Sabry and FSL works well.
