### ISSUE TITLE
Unable to access p697-appn

### ISSUE THREAD

**Issue by E-Claire** [norment/tsd_issues#52]
Logging in through windows and using putty I am unable to access p697-appn-norment01. When I enter my username and password I get the message “access denied”. 

Initially I thought this was only affecting me so I sent a ticket to tsd #4158221.

**Comment by ofrei** [comment]
I've had the same issue. It's still possible to login via Thinlink to Linux, and then ssh. 
From Windows a workaround is to use putty for connecting to p697-submit (or p697-submit2), and then ssh to p697-appn-norment01. 
I'm really curious what's wrong with connection from the Windows machine to the appnode via putty.

**Comment by ofrei** [comment]
I've requested additional software on p697-win02-pool / p697-win03-pool machines (RT 4160156). Currently they don't have putty, but I'm curious if with putty they would be able to connect to the appnode.
