### ISSUE TITLE
Able to login through VMware but can't login using Thinlinc. 

### ISSUE THREAD

**Issue by milinkim** [norment/tsd_issues#62]
Hi, 

It says “Invalid login, password or otp. Please try again” on Thinlinc login. 

Tusen takk, 
Milin

**Comment by ofrei** [comment]
@milrione Thank you for reporting this. This is marked as "solved" in TSD operational log ( https://www.uio.no/english/services/it/research/sensitive-data/log/ ) , but I don't think that's the case. It is still an issue for my user - exactly as you described it .  I've reported this [rt.uio.no #4226068], notified ``norment-hpc@medisin.uio.no``,   and forward directly to our TSD contacts.

**Comment by milinkim** [comment]
@ofrei Tusen takk! :) Hope it starts working again!

**Comment by idaElken** [comment]
Still an issue for me - can login via vmware, not thinlinc (p697)

**Comment by ofrei** [comment]
@idaElken @milrione This now works for me - both p33 and p697,  login through thinlink, login to self-service portal, import/export via http://data.tsd.usit.no/ . Is this still an issue on your end?

**Comment by milinkim** [comment]
@ofrei It finally works! Tusen takk!

**Comment by ofrei** [comment]
@milrione Great!
@Sandeek could you report this in our internal outage tracker (https://docs.google.com/forms/d/e/1FAIpQLSfyQtSd3intuKkb5O4hmmPq5UzX6EhuCk95ovNfHULc7DIBKg/viewform ) and close this ticket? Thanks!

**Comment by Sandeek** [comment]
@milrione  thanks for creating the issue. 

I updated our internal outage tracker. Please reopen this ticket if the login problem still persists.
