### ISSUE TITLE
Thinlic connection problem

### ISSUE THREAD

**Issue by milinkim** [norment/tsd_issues#63]
Hello! 

It keeps disconnecting and rebooting the session every few minutes. 
I've been having this issue most of the day. 

Tusen takk! 

Yours sincerely, 
Milin Kim

**Comment by ofrei** [comment]
@milrione Hi
Please submit an RT ticket (and paste here the number).

I haven't noticed problems today but I mainly worked from Windows VMWare - only connecting with thinlink for a few minutes at a time. 

Have you had a chance to try the RHEL8 login machine accessible via horizon vmware? I found this machine to be useful  - and so far it works well .
![image](https://user-images.githubusercontent.com/13171449/105914342-83be9700-602e-11eb-9119-51b5be4496b3.png)

**Comment by milinkim** [comment]
Hello!

It is working ok now! Tusen takk!!

Yours sincerely ,
Milin Kim

**Comment by ofrei** [comment]
@milrione good!
