### ISSUE TITLE
/cluster/projects/p697 mount hangs on p697-appn-norment01

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#64]
It seem that /cluster/projects/p697 mount hangs on p697-appn-norment01.
I can use p697-submit to access the data on cluster.
I can ssh p697-appn-norment01, and I can access tsd/p697/data/durable/
However I can not access /cluster/projects/p697 from p697-appn-norment01.

https://rt.uio.no/SelfService/Display.html?id=4249055

**Comment by Sandeek** [comment]
Issued resolved and logged the incident in https://docs.google.com/forms/d/e/1FAIpQLSfyQtSd3intuKkb5O4hmmPq5UzX6EhuCk95ovNfHULc7DIBKg/viewform

**Comment by ofrei** [comment]
@Sandeek It seem we have the same issue on p697-appn-norment01. Could you double-check and fix as before? If it happens again it is possible to investigate further? I think Sabry had some insights, either this was related to lack of space on /tmp folder or some other things...

**Comment by idaElken** [comment]
I have the same issue. on p697-appn-norment01

**Comment by ofrei** [comment]
@idaElken as a workaround you could use p697-submit or p697-submit2 machines - they work fine for me  as of now

**Comment by idaElken** [comment]
@ofrei . Thanks - I'll try that!

**Comment by Sandeek** [comment]
?Hi all,


I will check with Bart to find out the reason.


Best


Sandeep Karthikeyan
Data Engineer
CoE NORMENT, K.G. Jebsen Centre for Psychosis Research
Institute of Clinical Medicine, University of Oslo
Division of Mental Health and Addiction, Oslo University Hospital
www.med.uio.no/norment/english/<http://www.med.uio.no/norment/english/%20>
Office: Ullevål Hospital, Building 48
Tel: +47 41390032
________________________________

**Comment by Sandeek** [comment]
?Hi all,


The cluster is remounted and available again, unfortunately not able to figure out the reason for the issue :(


Best


Sandeep Karthikeyan
Data Engineer
CoE NORMENT, K.G. Jebsen Centre for Psychosis Research
Institute of Clinical Medicine, University of Oslo
Division of Mental Health and Addiction, Oslo University Hospital
www.med.uio.no/norment/english/<http://www.med.uio.no/norment/english/%20>
Office: Ullevål Hospital, Building 48
Tel: +47 41390032
________________________________

**Comment by ElizabethCorfield** [comment]
This issue is happening for me again.

**Comment by Sandeek** [comment]
?This is really strange, working with TSD on this.


Best


Sandeep Karthikeyan
Data Engineer
CoE NORMENT, K.G. Jebsen Centre for Psychosis Research
Institute of Clinical Medicine, University of Oslo
Division of Mental Health and Addiction, Oslo University Hospital
www.med.uio.no/norment/english/<http://www.med.uio.no/norment/english/%20>
Office: Ullevål Hospital, Building 48
Tel: +47 41390032
________________________________

**Comment by Sandeek** [comment]
Dear Claire,

Can you specify your p697 username? and from when you are facing this issue?

**Comment by ElizabethCorfield** [comment]
My username is p697-elizabethc.
I had been working on the appn node and then it suddenly just stoped working. So I tried re-connecting and could access tsd but not the cluster - which is when I  replied here.

**Comment by ElizabethCorfield** [comment]
I just tried logging into appn and accessing the cluster now (from the appn node) and I am able to - so super weird that the issue seems really intermittent

**Comment by Sandeek** [comment]
?Hi Claire,


There was a three minute outage on p697 cluster mount - hence the problem. Right now, it is not hanging.


Best


Sandeep Karthikeyan
Data Engineer
CoE NORMENT, K.G. Jebsen Centre for Psychosis Research
Institute of Clinical Medicine, University of Oslo
Division of Mental Health and Addiction, Oslo University Hospital
www.med.uio.no/norment/english/<http://www.med.uio.no/norment/english/%20>
Office: Ullevål Hospital, Building 48
Tel: +47 41390032
________________________________

**Comment by ElizabethCorfield** [comment]
Okay, thanks for looking into this Sundeep!!

In case this happens again - is there a certain amount of time that you would recommend waiting before reporting to see if the outage will just fix its self?

**Comment by Sandeek** [comment]
This issue has been persisting for some time now, TSD doesn't have much clue about why this occurs frequently, you can let me if and when it occurs.

**Comment by ElizabethCorfield** [comment]
Okay, thanks

**Comment by idaElken** [comment]
Unsure whether this is related but now do not get past login for neither:
p697-appn-norment01.tsd.usit.no; nor
p697-submit.tsd.usit.no

After apparently logging in successfully, it hangs:
<img width="762" alt="Screen Shot 2021-02-09 at 09 38 29" src="https://user-images.githubusercontent.com/4227962/107337420-9f0fb480-6aba-11eb-9d55-d40aeb75afaa.png">

Any advice welcome :-)

**Comment by idaElken** [comment]
Also hangs when trying to access 
p697-appn-norment01.tsd.usit.no
from VMware and putty.

But apparently known issue (sorry for posting):
https://www.uio.no/english/services/it/research/sensitive-data/log/nfs-hangs-on-submit-hosts.html

/Ida

**Comment by Sandeek** [comment]
?Hi Ida,

Can you try now?


Best


Sandeep Karthikeyan
Data Engineer
CoE NORMENT, K.G. Jebsen Centre for Psychosis Research
Institute of Clinical Medicine, University of Oslo
Division of Mental Health and Addiction, Oslo University Hospital
www.med.uio.no/norment/english/<http://www.med.uio.no/norment/english/%20>
Office: Ullevål Hospital, Building 48
Tel: +47 41390032
________________________________

**Comment by ofrei** [comment]
This is resolved (works for me, also reported in operation log).
@Sandeek please add to https://docs.google.com/forms/d/e/1FAIpQLSfyQtSd3intuKkb5O4hmmPq5UzX6EhuCk95ovNfHULc7DIBKg/viewform and close this ticket

**Comment by ElizabethCorfield** [comment]
I have this same problem again with the p697-appn hanging when I try and access the cluster. However, I am able to access the cluster through p697-submit.

**Comment by idaElken** [comment]
Same for me - p697-appn got slower and slower throughout the morning, until it crashed.Now using p697-submit
