### ISSUE TITLE
How does one view .png-files on p697?

### ISSUE THREAD

**Issue by idaElken** [norment/tsd_issues#65]
Hi, 

On p33, one can do:
xdg-open file.png
it opens in spite of a message:
"This tool has been deprecated, use 'gio open' instead."

On p697, if one does
xdg-open file.png
it gives this message:
gvfs-open file:///fullpath/file.png: error opening location: No application is registered as handling this file.

On p697, using FileBrowser instead, this error appears:
"Could not display 'file.png'
There is no application installed for PNG image files."

png-files are the output when visualizeing CNVs. To do visual QC of the CNVs called, I need to look at the pictures. I can transfer to p33 but that seems a bit backwards if there is a different solution. 

Do you have any advice?

/Ida

**Comment by ofrei** [comment]
Hi @idaElken 
Cool, I didn't know about ``xdg-open`` trick!
For p697, 
* if you login through ThinLink to Linux, you could  open a terminal, ``ssh -Y p697-appn-norment01``, and use ``eog``. Note ``-Y`` in the ssh command, that's important.
* If you login through VMWare Horizon to Windows, open a browser (eitehr IE or Firefox) and drag&grop the image to browser window.
Please let me know if it worked.
But we need  a better solution. It would be great to have ``eog`` on all login nodes, and a better viewer on windows.

**Comment by idaElken** [comment]
Brillant, thanks.  I'm teaching the computational scientist something about TSD - my proudest moment :-)

<img width="742" alt="Screen Shot 2021-02-05 at 08 50 11" src="https://user-images.githubusercontent.com/4227962/107004944-504add80-678f-11eb-8a9d-d6edbcd6269f.png">

No luck for eog on Linux. I can try the VMWare H to Windows later but for me personally, I may end up preferring moving to p697sharedp33 and view from the p33 linux end [and then erase it after, of course :-) ]

**Comment by ofrei** [comment]
>No luck for eog on Linux
Hm... it works for me. Could you  run ``hostname`` before ``ssh -Y``? It should show `` p697-tl01-l.tsd.usit.no``. I.e.  it is important to run ``ssh`` command on a new terminal window, so that it runs directly on the login node. If you have mulptile nested ssh sessions then ``-Y`` will not help to bring graphical user interface back to your login node

**Comment by idaElken** [comment]
Apologies - that WAS the issue - not having opened up a new terminal window. It works now so problem solved. :-) Thanks a lot!

**Comment by ofrei** [comment]
Great!
