### ISSUE TITLE
Unable to log into p697 windows

### ISSUE THREAD

**Issue by E-Claire** [norment/tsd_issues#66]
When I try logging into the windows version of TSD I get a loading failed error message due to the connection timing out.

**Comment by ElizabethCorfield** [comment]
tsd ticket number 4257468

**Comment by ofrei** [comment]
@E-Claire Same here. The web portal https://view.tsd.usit.no/portal/webclient/index.html is also not working . This must be not only p697 but all projects. No updates on operational log yet ( https://www.uio.no/english/services/it/research/sensitive-data/log/ ).

Thinlink still works for accessing linux.

**Comment by benjamso** [comment]
Fixed last night! :) Things should be back to normal again now.

**Comment by ofrei** [comment]
thank you @benjamso 👍
