### ISSUE TITLE
Error message when logging in to rhel7 from VMwareHorizon

### ISSUE THREAD

**Issue by codedbyanne** [norment/tsd_issues#68]
The error message I get is: This desktop currently has no desktop resources available. Try again later or contact system administrator.

I can log in fine from thinlinc, so resources are available...

**Comment by ofrei** [comment]
rhel7 VMWare machine is obsolete and had been removed. Please try rhel8 machines (either rhel8-01 or rhel8-02) -  if they don't work well please describe the problem here: https://github.com/norment/tsd_issues/issues/67
