### ISSUE TITLE
The user just added to another TSD project must reset password

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#7]
It would be great if users are do not need to change their password in their existing projects (e.g. p33) after getting an account in another TSD project (e.g. p697).
Also, since this is not intuitive, we need to tell this to users applying for access to a second TSD project.

**Comment by ThomasDoug** [comment]
Agree, issue to bring up in 12.02 meeting

**Comment by ofrei** [comment]
This is by design.
