### ISSUE TITLE
Install TemplateFlow for TSD

### ISSUE THREAD

**Issue by HaakonEngen** [norment/tsd_issues#70]
I'm trying to get a package called TemplateFlow (https://www.templateflow.org/) to work with TSD, in order to do some standardised QC on MR images. The issue is that it requires downloading and/or prefetching, but I'm not quite skilled enough to figure out how. Would you be able to help me out?

h.

**Comment by HaakonEngen** [comment]
Specifically, the issue I'm trying to resolve is the one described here:

https://github.com/poldracklab/mriqc/issues/820

**Comment by ofrei** [comment]
@HaakonEngen This is probably tracked by an RT ticket / already discussed elsewhere? Please close this ticket - best to move away from github tsd_issue to using slack channels.
