### ISSUE TITLE
jupyter command not found in p33-submit or p33-appn-norment01

### ISSUE THREAD

**Issue by zillurbmb51** [norment/tsd_issues#71]
Hi,
I was trying to use jupyter notebook on p33 but getting "jupyter command not found" (attached is my commands). Any help?

Best Regards
Zillur
![jupyter-command-not-found-in-p33](https://user-images.githubusercontent.com/12833907/110787148-4e33dd00-826d-11eb-9c9b-ba07cd4beca3.png)

**Comment by ofrei** [comment]
@zillurbmb51 jupyter needs to be installed (is not available by default). Did you ran the following command?
```
pip3 install --index-url=file:///shared/pypi/mirror/web/simple jupyter
```

**Comment by zillurbmb51** [comment]
@ofrei Thank you. 
When I used for the first time, I installed it and did not know that I have to install it again. However, It seems new installation works. But I am getting a new issue. In the browser, it asks for the token. If I give the token that is generated by jupyter notebook command , it shows "invalid credentials" (Attached).

![browser-invalid-credentials](https://user-images.githubusercontent.com/12833907/110790094-e97a8180-8270-11eb-9524-f76a2d337315.png)
![jupyter-token](https://user-images.githubusercontent.com/12833907/110790101-eaabae80-8270-11eb-80bb-50baf0a46ef4.png)

**Comment by ofrei** [comment]
> did not know that I have to install it again

Not really - once you install, it it should work. Let me know if it stops working again - this is not how it should be.
Note that you've started the jupyter on port 8889 - not 8888 (because 8888 was busy by someone else).
In you browser you need to type localhost:8889, and then provide the token.

**Comment by ofrei** [comment]
@zillurbmb51 This one is solved, right? I remember we discussed in on Zoom. Closing the ticket.
