### ISSUE TITLE
Unable to submit jobs in p697

### ISSUE THREAD

**Issue by zillurbmb51** [norment/tsd_issues#73]
Hi,
I am unable to submit jobs in p697. Attached is a job script. After submission nothing happens and even no error message appears. Any help? Best, Zillur
![job-submitted-p697](https://user-images.githubusercontent.com/12833907/111537880-447a1000-876c-11eb-8092-0cff8fd88af3.png)

**Comment by ofrei** [comment]
@zillurbmb51 It seem your jobs are running now
![image](https://user-images.githubusercontent.com/13171449/111541253-86a55080-8770-11eb-96e4-0064c2a93a37.png)

**Comment by zillurbmb51** [comment]
@ofrei , 
It seems submitting jobs in /tsd/p697...... is the problematic issue. If I submit cluster/projects/p697/.... it works!

**Comment by zillurbmb51** [comment]
@ofrei 
I am having this issue in the p33-appn-norment01. No error is showing. This time my working directory was in /cluster/..../users/...


![submit-job-p33](https://user-images.githubusercontent.com/12833907/112547595-3dca4900-8dbb-11eb-8f5a-cd72e48bc195.png)

**Comment by ofrei** [comment]
@zillurbmb51 could it be that your script is a noop? E.g. it had a top level ``for`` loop which is empty? Please add few ``echo`` statements in the very beginning and very end of your scripts - if they don't print anything then  yes it's a problem.

**Comment by zillurbmb51** [comment]
@ofrei , Thank you. Yes, the issue was with my script. I edited the script and it runs.
