### ISSUE TITLE
vim not installed

### ISSUE THREAD

**Issue by tirilgurholt** [norment/tsd_issues#75]
Could we have vim (and perhaps also gvim) installed on cluster? 

vim is not available on cluster nor home directory after "ssh -Y p33-appn-norment01" via p33-RHEL8-01-pool. 

Prior to ssh, vim is available in home directory.

**Comment by ofrei** [comment]
@tirilgurholt please submit an RT ticket to tsd-drift, they should be able to help with getting more software directly on app nodes or submit nodes. Alternatively, it should be possible to build "vim" from source code as described here: https://phoenixnap.com/kb/how-to-install-vim-centos-7 
Also, "vi" is already available - but I understand if you specifically need "vim" .
